version: '3.9'
services:
  mongo-rs0-1:
    image: "mongo-start"
    build: ./scripts/rs0
    ports:
      - "27018:27017"
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"
    networks:
      - mynetwork

  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27019:27017"
    networks:
      - mynetwork

  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27020:27017"
    networks:
      - mynetwork

  setup-rs:
    image: "setup-rs"
    build: ./scripts/setup
    depends_on:
      - "mongo-rs0-1"
    networks:
      - mynetwork

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
    networks:
      - mynetwork

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - mynetwork
  
networks:
  mynetwork:
    driver: bridge